stylesheets
menuCss
^ '
th.browseAnchor {
	background-color: #fcc302;
}
th.writeNew {
	background-color: #f7b6fa;
}
table#browseFilter {
	background-color: #fcc302;
	width: 100%;
}
table#writeMenu {
	background-color: #f7b6fa;
	width: 100%;
}
#hkamenu {
  background-color: aliceblue;
  width: 100%;
	border-collapse: collapse;
}
#hkalogo {
  text-align: left;
}
#hkauser {
  color: gray;
  text-align: right;
}
'