SystemOrganization addCategory: #'Heckaprompter-Experiments'!
SystemOrganization addCategory: #'HeckaPrompter-NewModel'!
SystemOrganization addCategory: #'Heckaprompter-Model'!
SystemOrganization addCategory: #'Heckaprompter-Seaside-Unused'!
SystemOrganization addCategory: #'Heckaprompter-Seaside-OAuth2'!
SystemOrganization addCategory: #'Heckaprompter-Seaside'!
SystemOrganization addCategory: #'Heckaprompter-Tests'!
