rendering
style
^ '
figcaption {
	text-align: right;
}

body form {
    width: 50%;
    margin-left: auto;
    margin-right: auto;
}

.formButtons {
	width: 50%;
	margin-left: 60%;
	margin-right: auto;
	margin-left: auto;
}

#linedArea {
	display: block;
	width: 100%;
	font-size: 20px;
	margin-left: auto;
	margin-right: auto;
	padding: 10px 0;
	line-height: 40px;
	background-image: linear-gradient(#eee 1px, transparent 1px);
	background-size: 100% 40px;
	border: 0;
	outline: 0;
}

.centered100 {
	width: 100%;
	margin: 0 auto;
}

.centeredinh {
	margin: 0 auto;
	width: inherit; 
}

#heckaclipart {
	margin: 0 auto;
	width: 50%; 
/*	background-color: blue; */
	clip-path: inset(0px 0px 0px 0px);
}

#heckablurb {
	margin: 0 auto;
	width: 50%; 
/*	background-color: blue; */
	clip-path: inset(0px 0px 0px 0px);
}

/*
.inputp {
	text-align: right;
	font-size: smaller;
}
*/

.blurbskip {
	text-align: right;
}

.blurbtext {
	text-align: center;
	height: 8em;
}


'