as yet unclassified
renderContentOn: html
	self renderMenuOn: html.
	html heading
		level: 2; with: 'play mode'.
	html heading
		level: 3; with: 'will:'.
	html 
		paragraph: 'let you link up your stories';
		paragraph: 'with other people''s stories';
		paragraph: 'with other people''s stories';
		paragraph: 'with your stories';
		paragraph: 'for playback as a narrative'.
	html heading 
		level: 3; with: 'coming summer 2019'.